version: "3.9"
services:
  db:
    image: "keinos/sqlite3:latest"
    
  web:
    build: .
    ports:
      - "8000:8000"
      
  redis:
    image: "redis:alpine"
    
    env_file:
    - "variables.env"
    
    